format_version: 4
pipelines:
  # Pipeline Name = build_and_package
  build_and_package:
    # Pipeline group name = kubernetes
    group: kubernetes
    display_order: 1
    environment_variables:
      DOCKERHUB_USERNAME: mattpiek
    materials:
      # Material Name = git
      git:
        git: https://github.com/mpiekunk/node-bulletin-board
        # Git feature - get latest version only (not history)
        shallow_clone: true
    stages:
    # Stage Name = build_stage
    - build_stage:
        # This can be set to manual if desired
        approval:
          type: success
        jobs:
          # Job Name = build_image
          build_image:
            elastic_profile_id: demo-app
            # These artifacts should be available to store
            artifacts:
            - external:
                id: bulletin-board
                store_id: dockerhub
                configuration:
                  options:
                    Image: ${DOCKERHUB_USERNAME}/bulletin-board
                    Tag: ${GO_PIPELINE_LABEL}
            tasks:
            - exec:
                arguments:
                # -c is required if you want bash shell interpretation (see docs)
                - -c
                - docker build -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL . -f Dockerfile.application
                command: /bin/bash
    - test_stage:
        # This can be set to manual if desired
        approval:
          type: success
        jobs:
          test_image:
            elastic_profile_id: demo-app
            tasks:
            - exec:
                arguments:
                # -c is required if you want bash shell interpretation (see docs)
                - -c
                - docker run -t $DOCKERHUB_USERNAME/bulletin-board:$GO_PIPELINE_LABEL npm test
                command: /bin/bash